### ISSUE TITLE
Typescript Type Issues from honeybadger-vue.d.ts

### ISSUE THREAD

**Issue by nicovigil1** [honeybadger-io/honeybadger-vue#440] opened 2020-06-29 21:33 UTC
## What are the steps to reproduce this issue?
1. Setup a simple Vue app with typescript
2. Try to add honeybadger-vue to vue app
![Screen Shot 2020-06-29 at 5 28 16 PM](https://user-images.githubusercontent.com/43397150/86057875-f2525c80-ba2d-11ea-96d6-7a5c2079da83.png)
3. Try & run `vue-cli-service serve` ( npm run serve )

## What happens?
Unfound Type: Honeybadger
![Screen Shot 2020-06-29 at 5 26 13 PM](https://user-images.githubusercontent.com/43397150/86058034-35accb00-ba2e-11ea-88cb-9f354f14a187.png)

## What were you expecting to happen?
a successful build

## Any other comments?
honestly just `type Honeybadger = any` at the top of the file would go a long way

## What versions are you using?
`.0.0.11`

**Comment by joshuap** [comment] 2020-07-06 18:35
@nicovigil1 is the [honeybadger-js](https://github.com/honeybadger-io/honeybadger-js) package being pulled in as a dependency? [It includes its own types](https://github.com/honeybadger-io/honeybadger-js/blob/master/honeybadger-js.d.ts); or is the issue is that those types aren't available in the `HoneybadgerVue` definition file?

**Comment by joshuap** [comment] 2020-08-27 17:51
This was fixed in https://github.com/honeybadger-io/honeybadger-vue/commit/13040274ab1e921d2253099441ddb785e195a7ff and is currently released in 0.0.12-beta.1.

**Closed by joshuap** 2020-08-27 17:51 UTC
Labels: bug
